### ISSUE TITLE
Difficulty dropping on bottom half of item with multiple divs

### ISSUE THREAD

**Issue by rahatarmanahmed** [marceljuenemann/angular-drag-and-drop-lists#126]
Here's an [example](http://plnkr.co/edit/onzijGPvpy8vwZOidbIv?p=preview)

Try to drag any item to the bottom half of another item. This is most apparent when dragging over the bottom half last item in the list, it is very difficult to drop something at the bottom of the list.

If you use just a single larger div inside the draggable div, then it works fine.

**Comment by marceljuenemann** [comment]
I can verify that. The problem is in isMouseInFirstHalf, specifically when calculating the mousePointer position. The 20px offsetTop of the bottom div would need to be added to calculate the mousePointer relative to the li element correctly.

Might be worth a try to refactor the whole positioning algorithm to be a bit more elegant and work in IE without workarounds. Actually, this might work correctly in (old versions of) IE, since it triggers the event on the ul element rather than the element it is actually over.

**Comment by rahatarmanahmed** [comment]
A rudimentary workaround for this is to have a div overlay on top of problematic list items like this while you are dragging something (use dragstart and dragend to determine when you are dragging). Here's my CSS

```css
.dropzone .dndOverlay {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 99999;
  opacity: 0;
}
```

**Comment by marceljuenemann** [comment]
The example in the opening post now works well with the new positioning algorithm in version 2.0
