### ISSUE TITLE
Splice happening too late, updates array incorrectly

### ISSUE THREAD

**Issue by JamesRosenthal** [marceljuenemann/angular-drag-and-drop-lists#145]
There's a flash of the old list item in the original list before the splash.  It's very short in the demo, but on my project the flash is so long the splice takes away the wrong list item because the length of the array is one item too long.  

Would the size of the objects in my lists affect this?

**Comment by dantheman999301** [comment]
I get this as well.

**Comment by danielnemetz** [comment]
Any workaround for this issue?

**Comment by splifo** [comment]
hi,
same here when in the same list(ordering). 
i have a vertical list.
it s happening when i drop item before others. (it work fine when drop after an item next(down)  the selected one )

Thanks for help and sorry for my english...

**Comment by marceljuenemann** [comment]
I haven't really experienced this problem. Anybody got a demo? Is this maybe because you are doing to much work in the dnd-drop handler?

**Comment by dantheman999301** [comment]
Actually I first reported it when it wouldn't fire whilst I was debugging
the dnd-drop handler.

Work around was just wrapping the code in a setTimeout with 0 ms fire time,
so that's a possibility if you need to do something time intensive in the
handler.

**Comment by EduardoMichel** [comment]
I see that the dnd-inserted event occurs before dnd-moved.  Is it supposed to happen this way?  

Here is a written example of how the code runs in my project:

1.  Container contains [item1, item2, and item3].

2.  Item3, whose index is 2, gets dragged above item 1.

3.  Code creates a copy, resulting in [item3, item1, item2, item3].

4.  Splice kicks in, and the index is still 2.  item2 is removed.

5.  Final result is [item3, item2, item3].

Notes:  

This error only occurs when moving an element earlier in the list.
Reproduced on IE11, Chrome, and FF.
dnd-moved is the only callback used.
This happens with any amount of items.
I'm using Angular 1.4.8 with typescript.

I'm not really sure what the expected behavior/order of some things are.
Is the element insertion supposed to occur before dnd-moved is triggered?  Is the $index value supposed to update before dnd-moved is triggered?

I'll try to make a demo when  I get the chance.

**Comment by firomero** [comment]
I am using Angular 1.4.6, I am having the same issue in Chrome and FF, and as EduardoMichel said, i doesn't matter the amount of items.

**Comment by leobudima** [comment]
Have exactly the same issue as @EduardoMichel described...

**Comment by dantheman999301** [comment]
Just out of interest, have you tried wrapping the code inside your
functions in a set timeout? Would be good for the developer if we could get
a worked jsfiddle at least.

**Comment by leobudima** [comment]
I tried wrapping in setTimeout, as well as completely removing dnd-inserted callback. But since my page is somewhat busy, with around 20 lists, it's enough to try and move the item in one list a bit more quickly a couple of times for issue to manifest itself, even without any other callbacks, only dnd-moved.

**Comment by sabin-iliescu** [comment]
I am positively sure that you are tracking by index in your ng-repeat:
ng-repeat="item in items track by $index"

remove "track by $index" and all your troubles will be miles away :)

**Comment by marceljuenemann** [comment]
@sabin-iliescu I was thinking the same, using track by $index is the most likely problem for the reported problems. I don't see how taking to long in the event handler would lead to this, since everything is in a single thread and therefore just gets delayed.

**Comment by Dentosal** [comment]
For me removing `track by $index` fixed this problem. Thanks.

**Comment by shubhamkes35** [comment]
Stuck with same problem and my code heavily depends on $index. Is there any other work around other than to remove $index ?

Please help me

**Comment by Typhlosaurus** [comment]
@shubhamkes35 the advice is not to disable $index, but rather to use a different property/function to trackBy.  For example:

ng-repeat="job in jobs trackBy job.id"

You can still use $index in callbacks and expressions within the element.
