### ISSUE TITLE
Dragged element opactiy

### ISSUE THREAD

**Issue by damdoum** [marceljuenemann/angular-drag-and-drop-lists#147]
Hi, first thanks a lot for this nice module. 
I was wondering if there is a way to overwrite the default css for a dragged element or just to be able to drag it without any ghost effect.
Is there any way ?

**Comment by marceljuenemann** [comment]
The directive has no default CSS, there are just examples in the demos. You can modify the CSS however you want.

**Comment by MalleusMalefic** [comment]
damdoum-

Did you ever find the solution for this? I can't seem to find whatever is causing the ghosting effect or a way to override it.

**Comment by damdoum** [comment]
@MalleusMalefic 

No i didn't find a way to get rid of that ghost effect. I have just understood that is the default behavior when you are using the native html5 for drag and drop like this module... 

It also seems that is do-able  but i didn't find any example for that on the web.
 Don't forget to share the solution if you find it, i will too.

**Comment by marceljuenemann** [comment]
The ghost effect in the demo is caused by this line:
https://github.com/marceljuenemann/angular-drag-and-drop-lists/blob/822552b2b6fe28fa7675ec434c769fa96ba5e154/demo/advanced/advanced.css#L40

Again, this is demo CSS that you should NOT just copy&paste to your application without thinking about what CSS styles you want.

**Comment by damdoum** [comment]
Thank you a lot @marceljuenemann . i have tried to find that line on the code but nothing.. it seems that i was working without coffee this day.. 
:+1:
