### ISSUE TITLE
event.stopPropagation makes implementing scrolling while dragging in firefox/safari difficult

### ISSUE THREAD

**Issue by jjoedouglas** [marceljuenemann/angular-drag-and-drop-lists#151]
I'm trying to implement scrolling in firefox/safari while dragging elements (without making my users install a firefox/safari plugin) and noticed on pretty much all events there's an `event.stopPropagation()`.  For obvious reasons this really screws with detecting dragover events and properly scrolling the window.

Is there a particular reason `event.stopPropagation()` is used?  Does it enable some other behavior I'm unaware of?

Thanks, I know this might be difficult to answer directly.  An "I don't know" will make me happy, just wanted to check if there's an obvious reason I'm not aware of. :+1:

**Comment by marceljuenemann** [comment]
Good question. It's required for nested lists. For example, if dragover didn't stop propagation, the parent element would receive the event as well and show a placeholder.

**Comment by mcMickJuice** [comment]
Would it be possible to allow for an escape hatch of some sorts, something like passing in a configuration or dependent directive that allows for events to propagate?  The default behavior would remain as it is now however the user could opt in to events bubbling.

**Comment by JulienFr** [comment]
Hi, I am having the same problem here on another project for Firefox and NOT for Chrome and Edge.

Instead of doing a `event.stopPropagation()` that seems to have some side effects.
In the dragover callback I do `ev.target = "stopPropagation";` and check in the dragover callbacks of the descendants against the condition `if (ev.target === "stopPropagation") return;`.

What do you think? Or if how did you solve it in the end? 
Let me know.
