### ISSUE TITLE
Drag and Drop is duplicating in WINDOWS10 IE EDGE browser 

### ISSUE THREAD

**Issue by a002194** [marceljuenemann/angular-drag-and-drop-lists#172]
Drag and Drop is not working in IE10 EDGE browser. I given 2 events dropped and moved events to my item. Item Moved event is not hitting Although dropped event return successfully.

**Comment by morious** [comment]
Experiencing the same issue.

**Comment by marceljuenemann** [comment]
I can reproduce the issue on http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/advanced . The dropEffect is apparently always send as copy instead of move. Note though that this only happens if you set dnd-effect-allowed to copyMove, so if you only want to allow moving, just set it to move (or remove the attribute as move is the default).

**Comment by leobudima** [comment]
I have the same issue with latest version, in Chrome, even with dnd-effect-allowed set to "move" or without it.

**Comment by whenmanage** [comment]
I think the bug persists in Edge on Windows 10. OP, please specify:
Is it an Edge or an internet (IE) 10/11 problem?

**Comment by marceljuenemann** [comment]
This is fixed by a refactoring of the drop effect handling. There is a design doc with details in the Wiki.
