### ISSUE TITLE
Duplicate array issue

### ISSUE THREAD

**Issue by devzar5** [marceljuenemann/angular-drag-and-drop-lists#192]
1.) when i used drag-start here is drag functionality is fine but if i drag item out side the box , then it removed completedly . one more thing i use array in ng-repeat. so please give us a solution what will i do to resolved this issue.

2.) other thing if i use dnd-moved function in place of drag-start here it does not work and leave a console error.

(Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: item in itemFieldInfo, Duplicate key: string:Prime Flag, Duplicate value: Prime Flag
http://errors.angularjs.org/1.4.3/ngRepeat/dupes?p0=item%20in%20itemFieldInfo&p1=string%3APrime%20Flag&p2=Prime%20Flag
    at http://localhost:8080/pricing-ui/js/lib/angular.js:68:12
    at ngRepeatAction (http://localhost:8080/pricing-ui/js/lib/angular.js:27142:21)
    at Object.$watchCollectionAction [as fn] (http://localhost:8080/pricing-ui/js/lib/angular.js:15550:13)
    at Scope.$RootScopeProvider.$get.Scope.$digest (http://localhost:8080/pricing-ui/js/lib/angular.js:15683:29)
    at Scope.$RootScopeProvider.$get.Scope.$apply (http://localhost:8080/pricing-ui/js/lib/angular.js:15951:24)
    at HTMLUListElement.<anonymous> (http://localhost:8080/pricing-ui/js/lib/angular-drag-and-drop-lists.js:341:15)
    at HTMLUListElement.jQuery.event.dispatch (http://localhost:8080/pricing-ui/js/lib/jquery-1.10.1.js:5116:9)
    at HTMLUListElement.jQuery.event.add.elemData.handle (http://localhost:8080/pricing-ui/js/lib/jquery-1.10.1.js:4787:46) ) 

code which i have written 

<ul dnd-list="itemFieldInfo">
		            					<li ng-model="selected"  ng-class="{active:selected==item}" dnd-effect-allowed="move"  dnd-draggable="item"  dnd-moved="move($index);"  ng-repeat = "item in itemFieldInfo">
		            						 {{item}}</label>
		            					</li>	            							            					
		            				</ul>

**Comment by devzar5** [comment]
i was use track by $index but it does not leave any effect.

**Comment by marceljuenemann** [comment]
You should not use track-by $index, see https://github.com/marceljuenemann/angular-drag-and-drop-lists/issues/96 for more info. Other than that you don't really provide any information on how I can reproduce your issue. Please add a plunker demo if you think you found a bug.

**Comment by firomero** [comment]
I have read all recursive issues but can not find the problem, i am not using the 'track by' expression and when the target index is lower, it duplicates the item, and the application crashes, so I am trying to find the correct solution to the problem.

**Comment by droptt** [comment]
I'm almost sure he meant something like [this](https://plnkr.co/edit/gBdHvd).

**Comment by bartonsprings** [comment]
I have the similar issue but I track by a unique item ID property for my object (not $index). In my case some nested lists do see a performance impact by not using trackby. So unfortunately, I have to use the track by ...

Is it possible to:
1. Let user specify an attribute for property name they are tracking by, something like: track-by-id="myID". 
2. You then look in the item object to see if that property exists.
3. If it exists, then when copying the item before moving the object, you generate a fake/temp property for that item object and use the original value in this property. Now delete that original property from original object. Since the element is hidden this should not cause any issue.
4. After item is dropped, anyway the old item will be delete. If drop failed then simply recreate the original ID from temp property and release the item to be shown.

Could possibly also have the case that if user attribute track-by-id=0 then it means they are tracking by $index and all other cases it is simply user specified tracking property name.

Would this work?

**Comment by dlombardi** [comment]
I'm running into this issue as well.  track by 'foo' does not prevent a duplicate item to be added to the array in dnd-list so the feature crashes.  After it crashes with the error message in OP's comment you are then unable to add new items thus forcing a refresh of the component.
