### ISSUE TITLE
How to drag table COLUMNS using this directive?

### ISSUE THREAD

**Issue by Parthvora** [marceljuenemann/angular-drag-and-drop-lists#201]
Hello,

Is there any way that I can use this directive to reorder table columns using its drag & drop feature and get new column order in callback function? Column should be draggable  by using its header tag < th > .

I know there are other directives which provides such feature, but I have tried all of them and they are not compatible with my project in one or another way.

**Comment by marceljuenemann** [comment]
You won't be able to see the entire column while dragging, since columns are no HTML elements, but other than that I see no reason why this wouldn't work. You need a model with all your column names, and then use the directive on the th elements. Once your model changed after the user drag and dropped a th element, your table should re-render.

**Comment by gauravg418** [comment]
Hi marceljuenemann,

Can you please provide a code sample, how to change order of columns with drag drop. It will be very appreciable.

Thanks.
