### ISSUE TITLE
how to get drop elements on dragover callback or any other callback functions?

### ISSUE THREAD

**Issue by nisr19** [marceljuenemann/angular-drag-and-drop-lists#207]

**Comment by marceljuenemann** [comment]
Currently there is no way to do that, you'll have to work around that by storing the object in some global variable in the dnd-dragstart callback and then you can read it out during dnd-dragover.

Some background on that: The HTML5 API uses native drag & drop and therefore does not allow you to read the data unless the user performs a drop. This is for security reasons, since the user might be dragging sensitive data and just happen to drag it across the browser window. We could, however, do the same workaround with a global variable in the directive, which would solve the problem for all cases where you don't use dnd-external-sources.

**Comment by marceljuenemann** [comment]
From 2.1.0, you can use dnd-callback to do that, see [this demo](http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/advanced). It does not work together with dnd-external-sources though.
