### ISSUE TITLE
Drag'n'Drop between 2 tables

### ISSUE THREAD

**Issue by R-iskey** [marceljuenemann/angular-drag-and-drop-lists#215]
Hi all !
If I have 2 tables. Can I drag and drop items with <tr> from 1 table to 2nd ?

**Comment by marceljuenemann** [comment]
Of course, did you even look at the demo?

**Comment by R-iskey** [comment]
Thank for your response.
Yeah I see , But I have 2 tables like this

`<table id='table-1'>
 <tbody>
  <tr dnd-list="vm.templates.header"
       dnd-draggable="header"
        ng-repeat="header in vm.templates.header">
        <td>
           <a href="javascript:void(0);" >{{ header.title }}</a>
        </td>
   </tr>
</tbody>
 </table>`

and table 2

`<table id='table-2'> 
       <tbody >
                    <tr dnd-list="vm.containers">
                    </tr>
      </tbody>
</table>`

I want to copy item from table 1 to table 2, how can I realize this ?

**Comment by marceljuenemann** [comment]
Your table2 doesn't have any elements. The directive doesn't create any DOM elements, it will just insert Javascript objects into your model, so you will at least need a ng-repeat

**Comment by zigkasg** [comment]
Hi, 
Could you please give me the url of a complete demo of drag and drop in tables instead of lists?
Sorry if it has been mentioned before..
Thanks
George

**Comment by marceljuenemann** [comment]
I don't see anything special about tables, just replace all uls with table and all lis with tds

**Comment by ninchica** [comment]
But, how to set placeholder class on table?
It will add` <li class="dndPlaceholder></li>` by default, but I want for placeholder tr element.
And descendant of the `<table>` is `<tbody>`

**Comment by zigkasg** [comment]
thanks for your help.
I will try and I might come back

**Comment by maryilewis** [comment]
I replaced ul with tbody and li with tr, and it's not working for me. [codepen](https://codepen.io/maryilewis/pen/YVqGgw). It works _ok_ in FireFox (background color doesn't show correctly, but it works), but when dragging an option in Chrome and IE I encountered the following:

Having `<li class="dndPlaceholder></li>` as the placeholder only takes up the first cell of the row, and the table element is exposed for the rest of the cells in the row. This looks bad if you have a background color on dndPlaceholder, and more importantly it breaks 'dragleave': 
`var newTarget = document.elementFromPoint(event.clientX, event.clientY);` comes back as the table
listNode is the tbody
`listNode.contains(newTarget)` is always false because the tbody does not contain the table
`stopDragover();` is called repeatedly, causing the placeholder to flicker rapidly. It's not usable.
You can see this in the codepen - Drag and hold with your cursor over the right column, top half of the row. The tds are blue, the placeholder li is green, and the table is red.

I've tried fixing this using CSS with no luck. Specifically, I changed dndPlaceholder to display: table-row instead of display: block and added height (since min-height doesn't work on table elements). Unfortunately, that just made placeholder altogether invisible and the flickering worse. I tried several other things (adding colspan, adding width), but browsers are very picky about table elements.

I haven't figured out a simple way to get it working properly without changing the angular-drag-and-drop code (in getPlaceholderElement, conditionally insert something like `<tr class='dndPlaceholder'><td colspan='1000'></td></tr>` instead of `<li class='dndPlaceholder'></li>` if element is a tbody). Besides, of course, formatting a list to look like a table.

Any help would be appreciated.

**Comment by cfpinto** [comment]
I know this is an old thread but... Why not create your own placeholder? see [codepen](https://codepen.io/anon/pen/xrGNGz)

**Comment by nandhacse** [comment]
Hi,

I have 3 tables in view. first(1st) and last(3rd) have some values in ng-repeat(say item1,item2,...). In the second, user can drag an item (say item1 in any position) and drop in it(second table). The dropped item should be in the same position where in the third table item placed.

**Comment by nandhacse** [comment]
![capture](https://user-images.githubusercontent.com/9796052/31213307-8a614096-a9c3-11e7-87d1-ef20c6496e4e.JPG)
![capture2](https://user-images.githubusercontent.com/9796052/31213306-8a5c0f0e-a9c3-11e7-8e31-507570bfc427.JPG)
These pictures describe what I want to do.. any help would be appreciated. thanks in advance

**Comment by nandhacse** [comment]
i can't do it with tables. but with uls and lis working fine.
