### ISSUE TITLE
Swap items to preserve list order on non-affected items.

### ISSUE THREAD

**Issue by niclaslindberg** [marceljuenemann/angular-drag-and-drop-lists#216]
Hi!

I have a list:
A
B
C

If I drag A->C I get
B
C
A

Instead I would like A and C to swap positions. As in: 
C
B
A

Is this possible? 

Thanks for an otherwise easy to use lib.

**Comment by marceljuenemann** [comment]
If you write your own dnd-drop callback you do pretty much anything, maybe take a look at this demo: http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/multi

My idea for this would be:
1. In dnd-draggable, send the $index instead of the item
2. In dnd-drop, perform the swap of items with the index that was passed and the old $index (passed as item).
3. Probably do nothing in dnd-moved
4. Probably you don't want to show a placeholder, but instead apply some CSS class to the element that you would swap with. You can do that in dnd-dragover.

**Comment by niclaslindberg** [comment]
Hi Marcel. Thanks for your mail! I tried your solution and I noticed a very strange thing:
When I move an element upwards the newIndex and oldIndex are correctly defined but when I move an element downwards the newIndex is to high (+1) and the oldIndex is "undefined". Any ideas of why this is happening? Thanks for any help! :)

**Comment by marceljuenemann** [comment]
That's because when you start dragging, the element is not removed from the list, it is just hidden with CSS (in the demos at least). See #54 for more info. I don't know what you mean by oldIndex, the directive doesn't provide such a thing.

**Comment by niclaslindberg** [comment]
Thanks for your answer. I managed to work around it. 
`"dndDropped" : function(e,newIndex,oldIndex) {
            //Workaround when dragging downwards.
            oldIndex = oldIndex!==undefined ? oldIndex : 1;
            if(oldIndex<newIndex) {
                newIndex--;
                oldIndex--;
            }`

**Comment by roshanreddy20** [comment]
Do you have a working copy for this,maybe a jsfiddle file?

**Comment by rajatlr** [comment]
To swap across two list, Should I send $index and index from dnd-draggable
