### ISSUE TITLE
Is it possible to force the dndPlaceholder to appear on empty lists?

### ISSUE THREAD

**Issue by Deklin** [marceljuenemann/angular-drag-and-drop-lists#231]
If i'm moving from one list to another, i'd like the placeholder to auto-appear on empty lists so the user knows exactly where they can drop it to. Is this possible?

**Comment by fberthel** [comment]
Hey Deklin,

we're working with dnd-lists on our web-app and had/have the same need for placeholder to be displayed when second list is empty.

For now this is the simplified workaround used within our solution:
```html
<ul dnd-list="list">
    <li ng-repeat="item in list" dnd-draggable="item"></li>
</ul>
<ul ng-if="list2.length" dnd-list="list2">
    <li ng-repeat="item in list2" dnd-draggable="item"></li>
</ul>
<ul ng-if="!list2.length" class="drop-hint">
    drop here
</ul>
```

```css
.drop-hint{
    border: 2px dashed #bbb;
    -webkit-border-radius: 4px;
    -moz-border-radius: 4px;
    border-radius: 4px;
    padding: 10px;
}
```

Don't know if there was a default placeholder style or if it was styled within the example, so that's our custom styling for the element. (removed all bootstrap and other custom elemts, attributes and styles)
It's working for us, but it's not clean and I would be very interested in a more elegant way of doing this :)

This html should be a little cleaner: (not tested, but should be straight forward)
```html
<ul dnd-list="list">
    <li ng-repeat="item in list" dnd-draggable="item"></li>
</ul>
<ul ng-if="list2.length" dnd-list="list2" ng-class="{'drop-hint': !list2.length}">
    <li ng-repeat="item in list2" dnd-draggable="item"></li>
    <span ng-if="!list2.length">drop here</span>
</ul>
```

I just notice I'm not sure about the default drag/hover-placeholder, but I also don't know what you aim for in that case (both placeholders visible vs 'drop-hint' only if list is empty).

Hard to phrase everything exactly.. hope you understand what I'm trying to say :)
Good luck and lets hope for a better solution.

**Comment by marceljuenemann** [comment]
The placeholder will always appear if a drop is possible. That's the way it should be, you should never display the placeholder if dropping wouldn't actually insert the element.

Are you maybe just tripping over a CSS problem where your ul has zero height and therefore dropping into it is not possible?!
