### ISSUE TITLE
Elements dropped one position too low if non draggable element before them

### ISSUE THREAD

**Issue by cschwaderer** [marceljuenemann/angular-drag-and-drop-lists#244]
In my drag&drop list, there should always be one fixed list item at the top, which is not be dragged. Well, that works. However, it affects the behaviour of the other items. When moving an element upwards they are inserted one position too low. So, dragging an element from the bottom to the first possible position, will get it on the second on so on.

My (simplified) code looks like such:

```
<div ng-repeat="list in model">

    <ul dnd-list="list">

        <li dnd-draggable="null" dnd-disable-if="1==1" dnd-effect-allowed="none">Item not draggable</li>

        <li ng-repeat="item in list"
                            dnd-draggable="mesSidebar"
                            dnd-effect-allowed="move"
                            dnd-moved="list.splice($index, 1)">Normal draggable items</li>

    </ul>

</div>
```

What can I do here? Is this a bug?

**Comment by marceljuenemann** [comment]
The directive figures the index out by looking at the DOM, since it has one element more than the list, it can't determine the correct position. There's an easy fix though, add a dnd-drop callback, insert the element yourself at index - 1, and return true to tell the directive that you already took care of the insertion.

**Comment by cschwaderer** [comment]
Thanks!
It's no so trivial, though, since downward movements work as expected and the "index - 1" is just necessary for upward movements. And whenever I'll change my HTML structure (adding or removing another non-draggable li) I will have to modify my drop-handler. So, I'd suggest you'd better build your index based on draggable elements, filtering the DOM by the corresponding attributes.

**Comment by marceljuenemann** [comment]
There's no requirement to have list elements draggable at all, so that's not so easy either. But I still think the index - 1 should work, you're probably just tripping over the fact that the source element is still there, only hidden. See https://github.com/marceljuenemann/angular-drag-and-drop-lists/issues/54

Why does your element have to be a li in the first place? If it's more like a header, then making it an element outside the ul might be semantically more correct?
