### ISSUE TITLE
How to prevent dropping further elements into a container type

### ISSUE THREAD

**Issue by sajithpc** [marceljuenemann/angular-drag-and-drop-lists#246]
Is there any options available to prevent dropping another container type to an already existing container type. If we set dnd-disable-if attribute, it disables the dragging functionality, but it allows to drop further elements into it. Is there any way to check the incoming item type and decide whether to insert or not.

`<script type="text/ng-template" id="list.html">
    <ul dnd-list="list">        
        <li ng-repeat="item in list" 
            dnd-draggable="item"            
            dnd-effect-allowed="none"      
            dnd-disable-if="item.type == 'container'"
            dnd-moved="list.splice($index, 1)"            
            dnd-selected="models.selected = item"
            ng-class="{selected: models.selected === item}"
            ng-include="item.id + '.html'">
        </li>
    </ul>
</script>`

**Comment by zlovin** [comment]
I believe you should be able to use the dnd-drop expression. From the readme:
`dnd-drop` Optional expression that is invoked when an element is dropped on the list.
The following variables will be available:
- `event` The original drop event sent by the browser.
- `index` The position in the list at which the element would be dropped.
- `item` The transferred object.
- `type` The dnd-type set on the dnd-draggable, or undefined if unset.
- `external` Whether the element was dragged from an external source. See dnd-external-sources.

The return value determines the further handling of the drop:
- `false` The drop will be canceled and the element won't be inserted.
- `true` Signalises that the drop is allowed, but the dnd-drop callback will take care of inserting the element.
- Otherwise: All other return values will be treated as the object to insert into the array. In most cases you simply want to return the item parameter, but there are no restrictions on what you can return.

So you should be able to add a type of dropCallback function and return `false` if the element should not be insertable based on its type, else return `item` to allow insertion.

**Comment by sajithpc** [comment]
Thanks zlovin for the detailed explanation.
