### ISSUE TITLE
feature request - sorting only (constrain to list)

### ISSUE THREAD

**Issue by nihlton** [marceljuenemann/angular-drag-and-drop-lists#267]
would be kind of nice if the draggables could be constrained to their current list for sorting.

if you drag out of the element, the place holder remains at the last position, and if the user releases, its moved to that index.

i realize this might not be doable with the native dnd api - since the list wouldn't receive the dragend/drop event.. you'd need to capture mouse/touch events and interpolate - so maybe not a great idea... but it would be useful.

**Comment by marceljuenemann** [comment]
To clarify, you can already restrict it to one list with dnd-type and dnd-allowed-types, but I assume you were only talking about the placeholder positioning.

As you said it would be quite complicated since we don't receive any dragover event and it would definitely not work with dnd-external-sources. I also don't think the user experience is that much better (it's also inconsistent with native drag & drop), so not worth the hassle.
