### ISSUE TITLE
Nested Lists: Multiple items one column, none on the other

### ISSUE THREAD

**Issue by dannymac7** [marceljuenemann/angular-drag-and-drop-lists#289]
When there are multiple items on one column and not the other, the container glitches. Video here: http://screencast.com/t/iQSV8ngts6B

**Comment by marceljuenemann** [comment]
Yeah, the positioning algorithm just looks whether it is in the upper or lower half of the element you're hovering over. Since this might change when the placeholder moves, it can result in these unfortunate infinite loops. Changing the placeholder/container size in your application might fix it for you, but I don't have an idea how to fix this in general.
