### ISSUE TITLE
Prevent drag and drop to content editors like microsoft word outside the browsers.

### ISSUE THREAD

**Issue by Nitesh2206** [marceljuenemann/angular-drag-and-drop-lists#298]
What happens is when you drag and drop an element in microsoft word ,the whole json gets copied over there.This seems to be a security issue.Is there a way to prevent this.

**Comment by marceljuenemann** [comment]
Currently not, but I have a design document for a new data transfer mechanism for 2.0 that would prevent this:
https://github.com/marceljuenemann/angular-drag-and-drop-lists/wiki/Data-Transfer-Design

It's already implemented in the dev branch, I believe. A note on security: The security model of drag and drop is that any application can access the dragged data once the user dropped the element she is dragging. So even with the new model the external application could access the data, if the user chooses to drag and drop the data. Then again, I don't think it's really a security concern, since the user has access to the data anyways and has to perform the drop.

**Comment by marceljuenemann** [comment]
Fixed in 2.0
