### ISSUE TITLE
How do I highlight the node on dragover instead of adding placeholder before and after li

### ISSUE THREAD

**Issue by rskumargithub** [marceljuenemann/angular-drag-and-drop-lists#299]
Hi,

I have a tree structure in which am using "ul" and "li" tags.  whenever I dragging of element to li I have  to highlight the dropping node before dropping instead placing li as placeholder and then should allow me to drop there. 
Can you help me out on this  ?.

**Comment by marceljuenemann** [comment]
One thing to note is that the positioning algorithm will insert the element *after* an element if the mouse pointer is in the bottom half of that element. So you would want to highlight the next element and not quite the one you are hovering over.

One idea is to use the adjacent sibling selector in CSS https://developer.mozilla.org/en/docs/Web/CSS/Adjacent_sibling_selectors:

    .dndPlaceholder {
      display: none;
    }
    
    .dndPlaceholder + li {
      background-color: red;
    }

Two problems with this though:
* If you move an element over the position it was in previously, then you won't see any highlighting (because the previous element is the next li)
* What to do if the user moves is to the bottom of the list, rather than to the previous to last one?

Another idea, that might require a bit more code, is to make every element of the list a dnd-list and then always highlight if the user is dragging over that dnd-list. You will have to roll your own insertion though.

**Comment by rskumargithub** [comment]
Thank you for your reply. I am sorry for the delay due to out of work for some time.   Actually, what I was looking for is when I have tree nodes (using UL/Li) and while dragging an any li node from top to any other node (especially which does not have any children nodes) within on tree then I have to highlight the tree node where am hovering over and insert the li element underneath of that node but now its inserting the li element next to the node where I am hovering over like adding other child node for the same parent node but this is not the expected behavior per my requirement.

Right now , if I have child nodes for the node where I am hovering over then its placing li element  underneath of the node and works fine, but on the above scenario its not. Hope you clear about my requirement.  

do you have any idea for this scenario ?.

**Comment by marceljuenemann** [comment]
Well, there's a fundamental problem here, how do you decide whether the user's intent is to drop the node below or next to another node? I guess you'll need to have two drop zones (dnd-lists), and make sure that those elements never have a height or width of zero

**Comment by rskumargithub** [comment]
I understand what you are saying. how about this case : Actually when hover over the node which does not have any children then we need to drop the node under the node to associate the children for that.  In case if we hover over in between the nodes we can drop in between of the two nodes. ?.

**Comment by rskumargithub** [comment]
Hi,

Hope you are doing good.

Is this drag and drop is available for angular 2 as well?. Or can you
suggest is there any drag and drop available to use for angular?

Thank your again!


Thanks,
Sasi
