### ISSUE TITLE
handle for item

### ISSUE THREAD

**Issue by Maiti** [marceljuenemann/angular-drag-and-drop-lists#31]
hello, 
great plugin
can you add a handle to items
looks like http://jimliu.github.io/angular-ui-tree/trees.html in the "Tree 2" block

Thanks

**Comment by rbdone** [comment]
+1 Love this directive! I need handles in a couple use-cases though.

**Comment by ashleydavis** [comment]
+1 This is great, but I also need drag handles.

**Comment by marceljuenemann** [comment]
Wouldn't this already work by just creating a child element with draggable=false and just putting the content in there? The handle would be another child element that propagates the events to the dnd-draggable. I'm too lazy too create a plunkr right now...

**Comment by cmlenz** [comment]
@marceljuenemann AFAICT `draggable=false` on a child element doesn't actually stop the drag of the draggable container element. It would be trivial to implement that for `dnd-draggable`, of course, but I'm not a fan of littering the markup with `dnd-draggable=false`, basically blacklisting non-grabbers instead of designating the element that should be used as grabber/handle.

Another way to implement this would be by allowing the `dndDragstart` callback to cancel the drag. Then the user of the directive could check whether the event target is (or is inside of) the grabber element, and cancel the event if it isn't.

Concerning #35 – Specifying the class name of the grabber as an attribute on the `dnd-draggable` element does not strike me as the Angular way of doing this. Wouldn't it be better to add a child directive, say `dnd-grabber` that you attach to the grabber element(s)?

```html
<li dnd-draggable="item">
    <span dnd-grabber></span> {{ item.label }}
</li>
```

Implementing that would require `dnd-draggable` to expose a directive controller for communication (`require: '^dndDraggable'`). What do you think?

**Comment by cmlenz** [comment]
I've went ahead and made PR #48 to implement this suggestion, although calling the directive `dnd-handle` instead of `dnd-grabber`. The actual implementation (tracking mouse events on the handle elements) is very similar to the implementation by @rbdone in #35.

I would appreciate feedback, testing, etc.

**Comment by justinklemm** [comment]
I've tested @cmlenz's PR with the `dnd-handle` addition and it works perfectly. Great work! I'd love to see it merged.

**Comment by justinklemm** [comment]
Another approach for using handles with the current library is to use `dnd-disable-if` to disable dragging by default, then enable it with `ng-mousedown` on your handle element, like this:
```
<div dnd-draggable="step" dnd-disable-if="dragEnabled">
    <span ng-mousedown="dragEnabled = true" ng-mouseup="dragEnabled = false">Handle</span>
</div>
```
I had a to a little tweaking to properly reset `dragEnabled` because `ng-mouseup` wasn't always firing, but it's workable.

**Comment by onemenny** [comment]
is anyone looking into this? why is the pull request not merged?

**Comment by marceljuenemann** [comment]
I like the controller approach. Just by looking at the code I'm surprised that the mousedown/mouseup approach works, did you test that thoroughly?

I'll try to look into this some time soonish, when the weather is bad outside ;)

**Comment by cmlenz** [comment]
> I like the controller approach. Just by looking at the code I'm surprised that the mousedown/mouseup approach works, did you test that thoroughly?

Yeah, I did test it at the time and it worked well for me even in IE 9 IIRC. Why do you think it would not work?

**Comment by marceljuenemann** [comment]
I'm not too keen on using mouse events. There is no guarantee that a drag operation is performed by mouse, e.g. when using the iOS shim for touch events, or maybe there is some accessibility tool that allows dragging via keyboard.

Can't we just check event.target and its parent elements whether one of them is a registered handle?

**Comment by marceljuenemann** [comment]
One more thing worth discussing is whether the behaviour of dnd-draggable should really change depending on its children. Is it semantically more correct to have a "dnd-only-drag-this-via-a-handle" attribute?

**Comment by marceljuenemann** [comment]
I added a dnd-nodrag directive to the dev branch, you can try the [demo](http://marcel-juenemann.de/tmp/angular-drag-and-drop-lists-dev/demo/#/types). I'll merge it to master once I have tested it thoroughly.

It's not exactly what you requested, but I believe you can achieve the same thing in most cases and its much cleaner to implement. I'll consider to also add a handle directive if there are many people for whom dnd-nodrag is not sufficient.
