### ISSUE TITLE
Drop item into nested lists with some of them empty

### ISSUE THREAD

**Issue by bartonsprings** [marceljuenemann/angular-drag-and-drop-lists#322]
I saw all the issues filed regarding this question. Completely understand that it is working as planned with min-height > 0 and enough to have a drop zone for the item inside the empty list.

But here is the issue I am running into. My nested lists looks uniformly clean and without absurd items in between where the nested list is empty. By adding the min-height for all cases, the empty nested lists in this list of items now have awkward looking spaces here and there just to create drop zones. 

So, lets say we do want to have the min-height present for even the empty lists, BUT can we make that dynamic so that ONLY after the DRAGSTART event, that min-height is applied to the parent list OR when we are moving the cursor over the PARENT item that contains the nested empty list, the min-height gets applied (for only some time delay). User can drop inside it or just keep going.

Does this make sense? Could this be possible?

Thanks in advance. Great library and excellent work!

**Comment by marceljuenemann** [comment]
That sounds reasonable, but you'd have to build this on your own using the dnd-dragstart callback, since this directive has nothing to do with the CSS.

If the problem is only with child lists, an easier approach might be to conditionally set the min-height depending on the .dndDragover class of the parent.
