### ISSUE TITLE
Impossible to drag item to first place in FireFox

### ISSUE THREAD

**Issue by gen4sp** [marceljuenemann/angular-drag-and-drop-lists#36]
In FireFox placeholder never shown in first place, and its impossible to drag item to there. 
(talking about horizontal mode - http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/advanced    try it in FF)
Any ideas?!

**Comment by peazz** [comment]
I can confirm this bug as well and I must say its a pain in the rear.

**Comment by peazz** [comment]
Ok, I think I figured out this bug although a little late.

in the dnd-dragover function, its checking the index is more than 0, however, if it hovers over the first element then index > 0 will return false (hence no placeholder and cant select parent), try remove the dnd-dragover function from root element and it will work fine.

**Comment by hjansen** [comment]
They got me on that one, too. But its written clearly in the text above the example:

Callbacks: The directives offer various callbacks, which in this example will log the events to the console. Additionally, the callbacks on the dnd-list can prevent an element from being dropped. **In this example you can't drop elements in the first list position, because we are preventing that in the dnd-dragover callback.**

**Comment by marceljuenemann** [comment]
Yeah, sorry for the bad example, this is working as intended. PR for a better example welcome.
