### ISSUE TITLE
If you drag all elements out of a dropzone, you can never drop anything back into that dropzone

### ISSUE THREAD

**Issue by kylegoetz** [marceljuenemann/angular-drag-and-drop-lists#63]
To recreate:

1. Go to http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/advanced
2. Drag items 10–16 out of their container and into any other
3. Try to drag anything into the (now empty) container that previously had items 10–16
4. Witness nothing is droppable there anymore. You can't ever put anything back into that (now empty) container.

**Comment by ScottieR** [comment]
I think you can fix this by setting a min-height or adding padding to the container.  There has to be a droppable area that has enough of a dimension to be recognized as the drop target.

**Comment by kylegoetz** [comment]
Nope. The demo I linked to has a min-height of 120px for the UL.

**Comment by Evotica** [comment]
I assume that is due to "In this example you can't drop elements in the first list position, because we are preventing that in the dnd-dragover callback." 

Once you have empty container, you are trying to drop into the first position/index 0, which is prevented by the function dragoverCallback() return statement "return index > 0;", which returns false for index 0.

**Comment by kylegoetz** [comment]
That's the reason. Closing this issue.
