### ISSUE TITLE
$$hashKey issue

### ISSUE THREAD

**Issue by crisoberillo** [marceljuenemann/angular-drag-and-drop-lists#70]
I have a problem with this module that I have tryed to explain here:
http://stackoverflow.com/questions/30531007/angularjs-didnt-update-next-hashkey-when-using-angular-drag-and-drop-lists

**Comment by reubenmiller** [comment]
Just a few things that could be going on:
1. When saving the object to a database make sure you strip out the $$hash variable. The angular.copy function does this for you (check the docs). It is a good idea to not store the $$hash because it might call problems if it exists because angular might noy create a new one as it already exists (I'm not 100% sure this is correct but it's always better to be safe, plus it doesn't pollute  your data in mongodb) 

2. Using track by is possible, however the the directive needs to be modified slightly. On the drag start event (when it serializes the object data to the copy, you need to add a unique id (the one used by the track by statement in the ng repeat). This is because on a move action the object is copied to the new target before the item at the source is deleted from the array. This happens because the item at the source (of the move) is only hidden, then the new target position is created, then the dropped callback is triggered (when you have the splice call to remove the object from its previous position in the array.

I solve this by just appending "-" to my uuid property (used in my ng-repeat e.g. ng-repeat="item in collection track by uuid")
And on the dropped callback, after my splice call, I remove the "-" from the uuid (because the source item was removed by the splice())

It's a bit hacky but it worked for me.

**Comment by crisoberillo** [comment]
Thanks mate. This has been really helpful :)
