### ISSUE TITLE
Deferred execution of dropCallback?

### ISSUE THREAD

**Issue by im1dermike** [marceljuenemann/angular-drag-and-drop-lists#78]
This may be Angular functionality that I just don't know, but I'm trying to defer the return in the `dropCallback` method until after I get a response from the server, but it's not working.

    $scope.dropCallback = function (event, index, item, type, status) {
        TaskService.updateTask(item).then(function (data) {
            return data;
        }, onError);
    };

Unfortunately, it only seems to work when I have `return item;` at the bottom of the callback, but, of course, that doesn't have the updates from the server.

**Comment by teh-skrud** [comment]
See #52 

The problem I see is that the native DnD doesn't support async callbacks, i.e. 'dragend' is called as soon as the 'drop' callback returns (in fact 'dragend' called only if the return value of 'drop' is falsy, 'true' meaning 'cancel').

Async drop thus means async dragend, and you have to rewrite both callbacks such that they use angular promises.

**Comment by marceljuenemann** [comment]
JavaScript is single-threaded, there is no way to defer returning from a function.

I don't think its a good user experience to have the RPC calls inside the drag and drop logic, since they can take a long time and fail. I would rather perform any RPC calls after the drop and update the model. You can do that in the background, which might lead to complicated logic when the user is quicker than the RPC calls, or you just lock the model and UI and show a loading/saving spinner.
