### ISSUE TITLE
Cannot drop to the very first position (see from the advance demo)

### ISSUE THREAD

**Issue by vcardins** [marceljuenemann/angular-drag-and-drop-lists#87]

**Comment by marceljuenemann** [comment]
This is actually a feature of the demo, rather than a bug. See the help text: "Callbacks: The directives offer various callbacks, which in this example will log the events to the console. Additionally, the callbacks on the dnd-list can prevent an element from being dropped. In this example you can't drop elements in the first list position, because we are preventing that in the dnd-dragover callback."

I admit that it was a bad example and I should change the demo.

**Comment by MacKentoch** [comment]
Nice directives!

As you said it is intended and I confirm your directives are awesome.

 **Thanks I just needed these!**


If anyone wants to to be able to drop at first position just edit 
- in advance demo js file :  `demo/advanced/advanced.js` file

 ***just modify as below :***

 ````javascript
     $scope.dragoverCallback = function(event, index, external, type) {
          $scope.logListEvent('dragged over', event, index, external, type);
          //demo shows how to block 1st position — as an example
          //return index > 0;
          //no can drop fist position
          return index >= 0;
      };
